### ISSUE TITLE
MIME types on JS CSS

### ISSUE THREAD

**Issue by danmorriswales** [DDVTECH/mistserver#18]
Mime types showing as text/html causing cross origin issues in Chrome. Can JS and CSS Files please be updated to use correct mime types please

**Comment by Rokamun** [comment]
Hey Dan, 

Which URLS specifically have the wrong mime type? We'll happily fix them of course.

**Comment by danmorriswales** [comment]
It seems to be when I use the embed code, Initially it works fine but if I refresh it will tag incorrect mime types. I'm not sure if the embed code changes periodically which may cause the issue? I'm experiencing some erratic behaviour at the minute so I'm not entirely sure that this is the underlying issue.

**Comment by Rokamun** [comment]
That's certainly weird, but which files are causing the problem? 
player.js, player.css, json_stream.js, info_stream.js or is it a completely different JS / CSS file? I've been looking in my Chrome browser but they seem correct so far.

**Comment by Rokamun** [comment]
Hmm...

Do you happen to have a forwarding proxy or something like that in there as well? 

The MIME types seem to be set correctly as far as I can see in the code itself. Especially the .webm returning text/html is weird.

**Comment by Thulinma** [comment]
Looking into this, it seems that the problem is that the embed is displayed inside an HTML iframe, with the parent page setting the option "X-Frame-Options: sameorigin". This means it will refuse to load anything coming from a different host/port combination than the parent website itself.
If possible, remove that option. If that is not possible, it might be easiest to reverse-proxy Mist through your website to avoid the issue altogether. See this article for more details: https://news.mistserver.org/news/81/Using+MistServer+through+a+reverse+proxy

Hopefully that takes care of your issue! If you need further help, feel free to re-open this. 👍
