### ISSUE TITLE
Build for ARMv7

### ISSUE THREAD

**Issue by jinfanzon** [DDVTECH/mistserver#21]
Hi - I've bought several mistserver licences on the past, and wanted to try mistserver for ARM. I wanted to know, cause haven't seen any in the README, how to build for ARM

**Comment by Rokamun** [comment]
Hey Jose,

I'll send you an arm build to your account so you can give it a go. It's
the same as any other operating system, you can unpack the binaries and use
them or use the install script to install them. Though we've noticed that
some ARM builds require some manual input with our current install script.

With kind regards,

Balder Viëtor
Head of Testing

**Comment by Thulinma** [comment]
And, to more specifically address you question directly:
To compile Mist for ARM, nothing special needs to be done. Simply compile it on an ARM platform (or use a cross-compiler). It is easiest to do the compilation on the target platform directly, because then no special setup at all is required.

Our compilation scripts auto-detect cross-compiling and will enable a generator mode that is compatible with such environments. Specifically, the compilation uses a tool "sourcery" that translates binary files into C++ includes and is created during compilation. For cross-compiling, you need to provide a native version of the "sourcery" binary yourself, by placing it into the source directory before you start your compile. You can obtain this binary by doing a native compile first (the binary will be created in the build directory, alongside Mist's other binaries).

I'll make a note to add these details to our README. Thanks for pointing out the information was missing!
