### ISSUE TITLE
pushing to tiktok

### ISSUE THREAD

**Issue by mishcazzulani** [DDVTECH/mistserver#46]
hi there! i'm trying to push an rtmp stream to tiktok but i run into a problem with authentication. the url is something like this:

rtmps://push-rtmp-f5-va01.tiktokcdn.com:443/game/stream-XXX?expire=XXX&sign=XXX

looking at the log i see these lines:

Stripping target options: expire=XXX&sign=XXX
Received error response: NetStream.Publish.InvalidSign; func:OnStatus:func:RtmpStatusCode2NssError:invalid_sign

why is mistserver stripping part of the url? what can i do? many thanks!

**Comment by Thulinma** [comment]
Hey there!

Mist supports receiving further options are query parameters, so anything following a question mark symbol gets parsed as options.
If you want to forward such parameters unchanged, simply follow the URL with an extra `?` at the end, as we only parse parameters after the last question mark symbol in the URL.

So, instead of `rtmps://push-rtmp-f5-va01.tiktokcdn.com:443/game/stream-XXX?expire=XXX&sign=XXX` you'd use `rtmps://push-rtmp-f5-va01.tiktokcdn.com:443/game/stream-XXX?expire=XXX&sign=XXX?`

Hope that helps!

**Comment by Rokamun** [comment]
Hey there,

As explained in the manual
<https://mistserver.org/guides/MistServer_Manual_3.0.pdf> (2.4.1)
MistServer will strip anything of the stream URL from the last "?" as it
expects MistServer specific selection parameters there. In order to fix
your problem simply use your push url:

rtmps://
push-rtmp-f5-va01.tiktokcdn.com:443/game/stream-XXX?expire=XXX&sign=XXX

and add an additional ? to the end:
rtmps://
push-rtmp-f5-va01.tiktokcdn.com:443/game/stream-XXX?expire=XXX&sign=XXX?

We do plan to make some adjustments to the interface in the future to make
this a bit easier to spot when you're starting a push.

With kind regards,

Balder Viëtor
Head of Testing
